// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func hello(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"color:red; text-align:center;\">Hello, ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `demo.templ`, Line: 4, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(". How are you doing?</div><a href=\"/helloworld\">Login</a><div><section style=\"display:flex; justify-content:center; align-items:center; background-color: rgba(255, 228, 196, 0.849);\"><h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, ducimus illum. Ea dolore praesentium magni reiciendis aperiam doloremque facilis velit beatae, nisi, dicta aliquid harum sapiente sunt et eius dolores ex minus!</h1><p style=\"\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro, nihil odio neque velit qui consequatur non, expedita dolorem repellendus laboriosam voluptatibus fuga nisi sint, architecto accusamus maiores. A facere suscipit reprehenderit autem! Amet unde qui quisquam minus ex nostrum, officia atque possimus, a dolore magni illo voluptatibus ullam vel in dicta, quibusdam aspernatur reiciendis placeat dolor minima. Impedit tempora deleniti libero soluta eum repellendus quae saepe nesciunt quod, sint magnam alias perspiciatis dolorem quasi. Neque temporibus maxime illo voluptates deleniti similique dolorum et aspernatur nobis. Tenetur optio sunt cupiditate voluptatibus error officiis facilis commodi distinctio sed tempore amet, quaerat dolore ea obcaecati, unde earum nostrum doloremque. Delectus sit nostrum illo quibusdam, necessitatibus ea itaque, autem magnam, non soluta sed architecto.</p></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func loginHandler() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><div><form action=\"/api/login\" method=\"post\"><label for=\"email\">Email</label> <input type=\"email\" name=\"email\" id=\"\" placeholder=\"Email\"><br><label for=\"password\">Password</label> <input type=\"password\" autocapitalize=\"off\" autocorrect=\"off\" name=\"password\" id=\"\" placeholder=\"password\"> <button>Submit</button></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
