version: 2.1

# orbs:
#   aws-code-deploy: circleci/aws-code-deploy@3.0.0

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: tidy go modules
          command: go mod tidy
      - run:
          name: Build
          command: go build -o main
      - run:
          name: Retrieve env variables into .env
          command: | 
            echo 'DB_URI='${DB_URI} > .env \
            && echo 'SECRET_KEY='${SECRET_KEY} >> .env \
            && echo 'STRIPE_SECRET_KEY='${STRIPE_SECRET_KEY} >> .env \
            && echo 'STRIPE_PUBLISHABLE_KEY='${STRIPE_PUBLISHABLE_KEY} >> .env && \
            cat .env
      - run:
          name: AWS EC2 deploy
          command: |
            #upload all the code to machine
            scp -r -o StrictHostKeyChecking=no ./ ubuntu@13.236.1.107:/home/circleci-aws/
            #Run script inside of machine
            ssh -o StrictHostKeyChecking=no ubuntu@13.236.1.107 "./deploy.sh"

  # deploy:
  #   docker:
  #     - image: 
  #   steps:
  #     - run: # Install the AWS CLI if it is not already included in the docker image
  #         name: Install openssh
  #         command: sudo apt install openssh 
  #     - run: # Install the AWS CLI if it is not already included in the docker image
  #         name: Install awscli
  #         command: sudo apt install aws-cli 

  #     - run: 
  #         name: Deploy with codedeploy
  #         command: echo "deploying to codedeploy ..." \
  #           echo ${ssh_key} > ssh_rsa_key.pem
  #           ssh -i ssh_rsa_key.pem ubuntu@ec2-3-89-115-53.compute-1.amazonaws.com \
  #           "sudo apt update && sudo apt install -y python3-pip"
          

workflows:
  deploy_application:
    jobs:
      - build


