version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: tidy go modules
          command: go mod tidy
      - run:
          name: Build
          command: go build -o main
      - run:
          name: Retrieve env variables into .env
          command: | 
            echo 'DB_URI='${DB_URI} > .env \
            && echo 'SECRET_KEY='${SECRET_KEY} >> .env \
            && echo 'STRIPE_SECRET_KEY='${STRIPE_SECRET_KEY} >> .env \
            && echo 'STRIPE_PUBLISHABLE_KEY='${STRIPE_PUBLISHABLE_KEY} >> .env && \
            cat .env

      - run:
          name: Run
          command: ./main


workflows:
  sample:
    jobs:
      - build
